language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - LARAVEL_VERSION=5.0
  - LARAVEL_VERSION=5.1
  - LARAVEL_VERSION=5.2
  - LARAVEL_VERSION=5.3
  - LARAVEL_VERSION=5.4
  - LARAVEL_VERSION=5.5
  - LARAVEL_VERSION=5.6
  - LARAVEL_VERSION=5.7
  - LARAVEL_VERSION=5.8
  - LARAVEL_VERSION=6.0

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL_VERSION=5.5
    - php: 5.6
      env: LARAVEL_VERSION=5.6
    - php: 5.6
      env: LARAVEL_VERSION=5.7
    - php: 5.6
      env: LARAVEL_VERSION=5.8
    - php: 5.6
      env: LARAVEL_VERSION=6.0
    - php: 7.0
      env: LARAVEL_VERSION=5.0
    - php: 7.0
      env: LARAVEL_VERSION=5.1
    - php: 7.0
      env: LARAVEL_VERSION=5.2
    - php: 7.0
      env: LARAVEL_VERSION=5.3
    - php: 7.0
      env: LARAVEL_VERSION=5.6
    - php: 7.0
      env: LARAVEL_VERSION=5.7
    - php: 7.0
      env: LARAVEL_VERSION=5.8
    - php: 7.0
      env: LARAVEL_VERSION=6.0
    - php: 7.1
      env: LARAVEL_VERSION=5.0
    - php: 7.1
      env: LARAVEL_VERSION=5.1
    - php: 7.1
      env: LARAVEL_VERSION=5.2
    - php: 7.1
      env: LARAVEL_VERSION=5.3
    - php: 7.1
      env: LARAVEL_VERSION=5.4
    - php: 7.2
      env: LARAVEL_VERSION=5.0
    - php: 7.2
      env: LARAVEL_VERSION=5.1
    - php: 7.2
      env: LARAVEL_VERSION=5.2
    - php: 7.2
      env: LARAVEL_VERSION=5.3
    - php: 7.2
      env: LARAVEL_VERSION=5.4

before_install:
  - composer self-update >/dev/null 2>&1
  - composer require illuminate/cache:${LARAVEL_VERSION} --no-update
  - composer require illuminate/http:${LARAVEL_VERSION} --no-update
  - composer require illuminate/support:${LARAVEL_VERSION} --no-update

install: composer update --prefer-source --no-interaction

script: vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- travis_retry php vendor/bin/php-coveralls -v

branches:
  only:
  - staging
  - stable

notifications:
  email:
  - hello@hisorange.me

# Thanks for this awesome service @TravisCI!
